### ISSUE TITLE
Run the application using Kubernetes KIND

### ISSUE THREAD

**Issue by salaboy** [salaboy/from-monolith-to-k8s#2]
https://kind.sigs.k8s.io

The tricky thing here is to find out the correct configuration to be able to run all services in a laptop setup. I would start with 8GB ram and 4 CPUs. This might not be available in all laptops but I think that it is a good starting point. 

None of the services are tuned right now (for memory and CPU consumption) , we should do that in a different issue.

**Comment by salaboy** [comment]
In order to run the application with KIND, after KIND is setup and `kubectl` is configured against the cluster you can use `helm`. I will create an issue for myself to document this tomorrow.

**Comment by salaboy** [comment]
@mcruzdev tomorrow my morning I will document how to install with Helm for you to try this one.

**Comment by salaboy** [comment]
@mcruzdev done.. I think that you can follow this section to start trying out the application on Kubernetes KIND -> https://github.com/salaboy/from-monolith-to-k8s/blob/master/README.md#installing-the-application---no-pipelines

**Comment by salaboy** [comment]
I am sure that for the application to run on KIND we will need to also install vault.. so I've provided a link there to the installation instructions.. but let me know if you get stuck with that.

**Comment by salaboy** [comment]
For external secrets with Vault you can take a look at here: 

https://medium.com/craftech/manage-your-kubernetes-secrets-with-hashicorp-vault-25d2fb8119f

It gets quite complicated.. but I think that it is worth the research

**Comment by mcruzdev** [comment]
@salaboy thank you, I gonna try again tomorrow ;)
After, I will send a feedback

**Comment by salaboy** [comment]
this is done now..

**Comment by jeanlouisvanbelle** [comment]
Hi Mr. Salatino - I just started reading your book and I find it very enlightening. I am a novice and configured all on an older Windows 10 Pro laptop. It works now, but I would recommend novices the following to as not to waste too much time with figuring out the set-up:

1. When you have Windows as the main OS, then you must first install a linux VM. I installed Ubuntu. Docker and K8S are easy to install, but I had some problems with Helm. I think it is easier to use the Chocolatey Windows package manager than the binary files or the script. Also, when running the commands from PowerShell, you need to use PowerShell as an administrator from time to time (that is logical but I just note it to make sure other people lose less time than I did).

2. Using PowerShell as a command prompt requires one to effectively put the configuration information in a config.yaml file. Hence, I used this command on the PowerShell CLI to create the cluster: kind create cluster --name dev --config=C:\Users\...\config.yaml 

3. I created the config.yaml file with NotePad and, of course, novices should note they should use the yaml extention and not the txt extension. To be clear, the config.yaml file contains:
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
- role: worker
- role: worker

All fun ! Many thanks again and hopefully this helps people like me - who are not used to linux - to get rolling easily.  Kindest regards - Jean Louis
