### ISSUE TITLE
Update to Spring Boot 2.6.4 and Spring Cloud 2021.1.1, update to Java 17

### ISSUE THREAD

**Issue by mcruzdev** [salaboy/from-monolith-to-k8s#24]
We want to upgrade Spring Boot and Spring Cloud versions for `2.6.4` and `2021.1.1` respectively. 

- [ ] #25
- [ ] Upgrade Spring Boot and Spring Cloud versions **fmtok8s-c4p** ( when possible or necessary )
- [x] #33
- [ ] Upgrade Spring Boot and Spring Cloud versions **fmtok8s-email** ( when possible or necessary )
- [ ] Upgrade Spring Boot and Spring Cloud versions **fmtok8s-queue** ( when possible or necessary )
- [ ] Upgrade Spring Boot and Spring Cloud versions **fmtok8s-tickets** ( when possible or necessary )
- [ ] Upgrade Spring Boot and Spring Cloud versions **fmtok8s-payment** ( when possible or necessary )

**Comment by salaboy** [comment]
@mcruzdev I think that we should aim for Java 17

**Comment by salaboy** [comment]
I have an example project with Java 17, and this is all working fine: https://github.com/salaboy/fmtok8s-game-frontend/blob/main/pom.xml#L18

**Comment by mcruzdev** [comment]
Hi @salaboy should we aim to spring-cloud 2021.0.2 and spring-boot 2.6.7?

**Comment by mcruzdev** [comment]
> I have an example project with Java 17, and this is all working fine: https://github.com/salaboy/fmtok8s-game-frontend/blob/main/pom.xml#L18

Ok 👍 
Is the lts ☕
