### ISSUE TITLE
docker-compose for the entire app

### ISSUE THREAD

**Issue by salaboy** [salaboy/from-monolith-to-k8s#3]
Here are the paths for the docker images:
- gcr.io/camunda-researchanddevelopment/fmtok8s-agenda
- gcr.io/camunda-researchanddevelopment/fmtok8s-email
- gcr.io/camunda-researchanddevelopment/fmtok8s-c4p
- gcr.io/camunda-researchanddevelopment/fmtok8s-api-gateway

I think the best would be to use the `latest` tag for all the images. 

I would prefer you running the app in KIND instead of spending time on Docker Compose, but it might make some sense to have the docker compose option to show people the difference between KIND and Docker Compose.

**Comment by salaboy** [comment]
@mcruzdev should I close this? I don't think that we need this... feel free to close..

**Comment by mcruzdev** [comment]
I think that is not necessary to use docker-compose @salaboy
