### ISSUE TITLE
Using without Cloud Provider improvements

### ISSUE THREAD

**Issue by mcruzdev** [salaboy/from-monolith-to-k8s#8]
In my experience trying to use Vault with k8s cluster, I saw that is hard to configure

While the documentation will not describe how can use with Vault. I thought about removing these steps from documentation and I decide to use Kubernetes Secrets to be more simple.

https://github.com/salaboy/from-monolith-to-k8s/edit/master/README.md#L68

**Comment by salaboy** [comment]
@mcruzdev thanks a lot for this.. merged
